// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevTur.API.Models
{
    [Table("endereco")]
    public partial class Endereco
    {
        public Endereco()
        {
            Cliente = new HashSet<Cliente>();
            Funcionario = new HashSet<Funcionario>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Required]
        [Column("bairro")]
        [StringLength(255)]
        public string Bairro { get; set; }
        [Required]
        [Column("cep")]
        [StringLength(255)]
        public string Cep { get; set; }
        [Required]
        [Column("cidade")]
        [StringLength(255)]
        public string Cidade { get; set; }
        [Column("complemento")]
        [StringLength(255)]
        public string Complemento { get; set; }
        [Required]
        [Column("logradouro")]
        [StringLength(255)]
        public string Logradouro { get; set; }
        [Required]
        [Column("numero")]
        [StringLength(255)]
        public string Numero { get; set; }
        [Required]
        [Column("uf")]
        [StringLength(2)]
        public string Uf { get; set; }

        [InverseProperty("EnderecoIdFkNavigation")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [InverseProperty("EnderecoIdFkNavigation")]
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}