// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevTur.API.Models
{
    [Table("funcionario")]
    [Index("EnderecoIdFk", Name = "FKs4ik2nbyjsqnrb37ubwmkdyt8")]
    [Index("Cpf", Name = "funcionario$UK_rxosr8731eb3gbnlbt2mqfan8", IsUnique = true)]
    [Index("Email", Name = "funcionario$UK_t45qja1wnv0hu1cdw6vqjljgy", IsUnique = true)]
    public partial class Funcionario
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Required]
        [Column("cpf")]
        [StringLength(14)]
        public string Cpf { get; set; }
        [Column("data_nascimento", TypeName = "date")]
        public DateTime DataNascimento { get; set; }
        [Required]
        [Column("email")]
        [StringLength(80)]
        public string Email { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(80)]
        public string Nome { get; set; }
        [Required]
        [Column("telefone")]
        [StringLength(15)]
        public string Telefone { get; set; }
        [Column("data_admissao", TypeName = "date")]
        public DateTime DataAdmissao { get; set; }
        [Column("data_demissao", TypeName = "date")]
        public DateTime? DataDemissao { get; set; }
        [Required]
        [Column("senha")]
        [StringLength(255)]
        public string Senha { get; set; }
        [Column("endereco_id_fk")]
        public long EnderecoIdFk { get; set; }

        [ForeignKey("EnderecoIdFk")]
        [InverseProperty("Funcionario")]
        public virtual Endereco EnderecoIdFkNavigation { get; set; }
    }
}