// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DevTur.API.Models
{
    [Table("viagem")]
    [Index("ClienteIdFk", Name = "FKh2ia86xs9dvujq545myvga47o")]
    public partial class Viagem
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("data_fim", TypeName = "date")]
        public DateTime? DataFim { get; set; }
        [Column("data_inicio", TypeName = "date")]
        public DateTime DataInicio { get; set; }
        [Required]
        [Column("descricao")]
        public string Descricao { get; set; }
        [Column("gastos", TypeName = "decimal(19, 2)")]
        public decimal Gastos { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(255)]
        public string Nome { get; set; }
        [Column("orcamento", TypeName = "decimal(19, 2)")]
        public decimal Orcamento { get; set; }
        [Column("cliente_id_fk")]
        public long ClienteIdFk { get; set; }
        [Required]
        [Column("acompanhantes")]
        [StringLength(255)]
        public string Acompanhantes { get; set; }

        [ForeignKey("ClienteIdFk")]
        [InverseProperty("Viagem")]
        public virtual Cliente ClienteIdFkNavigation { get; set; }
    }
}